### PR TITLE
Add prettier-plugin-tailwindcss

### PR DESCRIPTION
**Pull request by ahmedrowaihi**
Prettier plugin for Tailwind CSS that automatically sorts classes based on our recommended class order. [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)

### CODE REVIEW

**Comment by ahmedrowaihi** [comment]
You mean the prettier version or the plugin I added ?

**Comment by juliusmarminge** [comment]
> You mean the prettier version or the plugin I added ?

Yep tailwind plugin do something special and need to support other plugins explicitely.

However i just checked and a PR was merge 3 days ago adding support for ianvs sorter so i guess next version of tailwind plugin will have support 

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/122

https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins

**Comment by its-monotype** [comment]
@juliusmarminge 
Is a prettier sorting plugin better than the [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort)

**Comment by ahmedrowaihi** [comment]
> > You mean the prettier version or the plugin I added ?
> 
> Yep tailwind plugin do something special and need to support other plugins explicitely.
> 
> However i just checked and a PR was merge 3 days ago adding support for ianvs sorter so i guess next version of tailwind plugin will have support 
> 
> https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/122
> 
> https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins

I see, should we keep the PR or close it?

**Comment by juliusmarminge** [comment]
> I see, should we keep the PR or close it?

This is not my repo - I just scrolled through and happened to see this so thought I'd just point it out.

**Comment by shadcn** [comment]
@ahmedrowaihi Yep. I use `eslint-plugin-tailwindcss` because of the reason @juliusmarminge mentioned. There's an issue with `prettier-plugin-tailwindcss`, the sort plugin and `pnpm`.

I'll check out the latest and see if it's fixed.

However, the eslint one has been working well so far. I might just keep it.

**Comment by ahmedrowaihi** [comment]
@shadcn yes I think that eslint plugin is good enough for now.
We may close this PR

**Pull request closed without merging**
