### PR TITLE
docs: add react with vite installation guide

### PR DESCRIPTION
**Pull request by samuelkurdz**

### CODE REVIEW

**Review by OwaisAD — APPROVED** [review]
works well

**Comment by shadcn** [comment]
@samuelkurdz Thanks so much for creating the docs for this. Can we move it to `installation.mdx`?

**Comment by dan5py** [comment]
> Can we move it to installation.mdx?

I was thinking the same thing. It would be great to have tabs in the `Installation` page for all the different frameworks.

**Comment by samuelkurdz** [comment]
> @samuelkurdz Thanks so much for creating the docs for this. Can we move it to `installation.mdx`?

@shadcn  Yes of course.
Although I initially created the `React with vite` page like a sub-page under installation.

```javascript
 {
  title: "Installation",
  href: "/docs/installation",
  items: [
    {
      title: "React with vite",
      href: "/docs/react-with-vite",
      items: [],
    },
  ],
},
```
but it did not appear as such.

**Comment by dan5py** [comment]
@samuelkurdz Something like this:

image

**Comment by samuelkurdz** [comment]
Is anyone on this? or can I?

**Comment by dan5py** [comment]
@samuelkurdz I don't think so, go ahead

**Comment by samuelkurdz** [comment]
@dan5py I kind of have a decision between the page quick links by the right.
so I want to share between the options I created.

**1.** 

Screenshot 2023-06-26 at 14 03 09








**2.** 
Screenshot 2023-06-26 at 14 01 38

**Comment by dan5py** [comment]
@samuelkurdz  I think the first is cleaner.

**Comment by samuelkurdz** [comment]
@dan5py PR updated.

**Review by dan5py — CHANGES_REQUESTED** [review]
You can remove the classnames from the components since they're already applied in [mdx-component.tsx](https://github.com/shadcn/ui/blob/main/apps/www/components/mdx-components.tsx) (also the wrapper `div`)

**Review by dan5py — APPROVED** [review]
👍

**Comment by shadcn** [comment]
@samuelkurdz This looks great. Question: do we want the following config in `tsconfig.json`?

```json
"baseUrl": ".",
"paths": {
  "@/*": ["./src/*"]
}
```

So that aliases such as `@/components/...` are resolved?

Here's a CodeSandbox I was testing: https://codesandbox.io/p/sandbox/shadcn-ui-vite-m9ry84?file=%2Ftsconfig.json%3A8%2C22

**Comment by dan5py** [comment]
Yeah, this would keep the same aliases for different frameworks. 

So I suggest keeping the `@` alias format:

```diff
- alias: [{ find: "src", replacement: path.resolve(__dirname, "./src/") }],
+ alias: [{ find: "@", replacement: path.resolve(__dirname, "./src/") }],
```

And also the CLI prompt would remain the default ones:

```diff
- Configure the import alias for components: › src/components
- Configure the import alias for utils: › src/lib/utils
+ Configure the import alias for components: › @/components
+ Configure the import alias for utils: › @/lib/utils
```

**Comment by samuelkurdz** [comment]
@shadcn @dan5py
I experimented with your suggestions and it works if the `tsconfig.json` and `vite.config.ts` updates comes first.
So I will be updating this PR. Thanks.

Without that
```
Configure the import alias for components: › @/components
Configure the import alias for utils: › @/lib/utils
```
This above created an `@` folder in the root of the application that contains the components and utils file.

**Comment by dan5py** [comment]
> This above created an `@` folder in the root of the application that contains the components and utils file.

Yeah I'm aware of this. Just add the paths on the `Edit tsconfig.json` step.

**Comment by samuelkurdz** [comment]
> > This above created an `@` folder in the root of the application that contains the components and utils file.
> 
> Yeah I'm aware of this. Just add the paths on the `Edit tsconfig.json` step.

Updated!

**Review by dan5py — APPROVED** [review]

**Comment by shadcn** [comment]
> By the way, this is my first open-source contribution. Thanks for being nice!

No. Thank you. This is amazing!

**Comment by dan5py** [comment]
> By the way, this is my first open-source contribution. Thanks for being nice!

You did a really great job! 🎉

**Comment by CarlosZiegler** [comment]
Really nice !!!!!! Thanks for supporting Vite :)

**Comment by CarlosZiegler** [comment]
I am curious, CLI will be work on this ? @shadcn @samuelkurdz ?

**Comment by dan5py** [comment]
Hi @samuelkurdz,
@mdloop is developing the installation page with Tabs where the content of each framework has its own file (to keep things cleaner). If #753 gets merged I'd like you to add the docs for vite that you created.

**Comment by shadcn** [comment]
@dan5py Should this one be merged first or #753?

**Comment by dan5py** [comment]
> @dan5py Should this one be merged first or #753?

First #753. Then @samuelkurdz will update this PR.

**Comment by dan5py** [comment]
@samuelkurdz The new layout has been merged to main. You can now add the vite docs. Thanks in advance 💪.

**Review by dan5py — APPROVED** [review]
Perfect, thank you.

@shadcn this is ready to merge.

**Comment by shadcn** [comment]
Awesome. Thanks so much @samuelkurdz

**Review by shadcn — APPROVED** [review]

**Pull request merged**
