### PR TITLE
Fix accordion trigger icon shrink when text get to long

### PR DESCRIPTION
**Pull request by MohamedMujtaba**
Subject: Fix Accordion trigger icon shrinking issue

Body:

Hi ,

   I've made some updates to fix an issue with the Accordion trigger icon shrinking when the text gets too long. Here are the changes I've made:

- Added the class name "shrink-0" to the ChevronDown icon to prevent it from shrinking
- Added the class name "text-left" to the AccordionPrimitive.Trigger to left-align the text

   I've tested these changes locally and they fix the issue. Please review and merge the pull request when you have a chance.

Thanks,

### CODE REVIEW

**Comment by jocarrd** [comment]
related [issue](https://github.com/shadcn/ui/issues/316)

**Review by its-monotype — APPROVED** [review]

**Comment by jocarrd** [comment]
👀

**Review by jocarrd — APPROVED** [review]

**Comment by MohamedMujtaba** [comment]
@jocarrd could you plz give me your twitter

**Comment by dan5py** [comment]
#717 solved the issue. Please close this PR.

**Pull request closed without merging**
