### PR TITLE
feat(Table): Add Table component

### PR DESCRIPTION
**Pull request by multiwebinc**

### CODE REVIEW

**Comment by multiwebinc** [comment]
I'm not sure if you would prefer to separate the table wrapper into its own component. It's simpler how I have it now (since it requires less markup), but might be a bit less flexible for styling. Or maybe I could make it a sibling component absolutely positioned under the actual table and add the rounded borders to the corner cells of the table.

**Comment by shadcn** [comment]
This looks great. I've been testing `tanstack-table` integration. I'll give this a try with this component and report back.

**Comment by multiwebinc** [comment]
Since `tanstack-table` might be overkill for simple tables, you might want to consider adding it as a separate component, sort of like how MUI has [Table](https://mui.com/material-ui/react-table/) for simple tables and [DataGrid](https://mui.com/x/react-data-grid/) for more advanced uses.

This component looks OK, but it would be nice if there were more colors to choose from. There are a couple of issues open about that, so if you let me know what direction you want to head, I would be willing to work on a PR for that as well if you like.

**Comment by Rugz007** [comment]
> This looks great. I've been testing `tanstack-table` integration. I'll give this a try with this component and report back.

Hey, if you want I can give tanstack table a look and make a PR

**Comment by willopez** [comment]
I vote for using `tanstack-table` and have a basic example that people can build upon.

**Comment by mhaidarhanif** [comment]
> Since `tanstack-table` might be overkill for simple tables, you might want to consider adding it as a separate component, sort of like how MUI has [Table](https://mui.com/material-ui/react-table/) for simple tables and [DataGrid](https://mui.com/x/react-data-grid/) for more advanced uses.

I vote to support either and differentiate the name (Table vs DataGrid vs other) to fulfill both or more expectations down the road.

**Comment by shadcn** [comment]
Thanks for the suggestions.

As @multiwebinc said, making tanstack-table the default would be overkill for most app. 

I suggest we move forward with @multiwebinc `<Table />` primitive and add `tanstack-table` as an example.

**Comment by shadcn** [comment]
@multiwebinc I'm going ahead and merge this. I have some more updates in another branch incoming. Thank you.

**Review by shadcn — APPROVED** [review]

**Comment by shadcn** [comment]
@multiwebinc I pushed table and data table yesterday. Couldn't find you on Twitter to credit you for starting the work on table. But I merged this PR so you should get the commit credit.

HMU on Twitter if you're around.

**Pull request merged**
