### PR TITLE
fix: scroll to top for docs tab

### PR DESCRIPTION
**Pull request by mertcanaltin**
@shadcn I made a small touch can we use this #3 

[preview](https://s3.gifyu.com/images/chrome-capture-2023-0-24.gif)

### CODE REVIEW

**Comment by mertcanaltin** [comment]
> @mertcanaltin I think this code is not safe for all, if sidebar is multi level or some thing like that, It can click and don't change view in right side ( don't scroll view )

yes i totally agree

this is just a temporary solution

**Comment by jomefavourite** [comment]
I feel this is needed asap 😑

**Comment by shadcn** [comment]
Known issue with scroll restoration. The Next.js team is looking into this.

**Comment by mertcanaltin** [comment]
I'm closing this place because everything is fine, thank you very much everyone @shadcn

**Pull request closed without merging**
