### PR TITLE
Next.js 13.2 Upgrade

### PR DESCRIPTION
**Pull request by elliot**
Upgrades `playground` and `next-template` to [Next 13.2](https://nextjs.org/blog/next-13-2)

- [x] Migrate to [Metadata API](https://beta.nextjs.org/docs/api-reference/metadata)
- [x] Enable [Typescript plugin](https://beta.nextjs.org/docs/configuring/typescript#using-the-typescript-plugin)
- [x] Remove `display: swap` as it is now built in

> **Note**
> Upgrading `www` currently blocked by https://github.com/contentlayerdev/contentlayer/issues/386

<details><summary>Build Stats: next-template</summary>

Before
```
Route (pages)                              Size     First Load JS
┌ ○ /                                      34.6 kB         113 kB
├   /_app                                  0 B            78.2 kB
└ ○ /404                                   181 B          78.4 kB
+ First Load JS shared by all              85.5 kB
  ├ chunks/framework-2647c7e378e02044.js   45.2 kB
  ├ chunks/main-9fee79d2c98001b5.js        26.8 kB
  ├ chunks/pages/_app-a38f8853e697b35d.js  5.13 kB
  ├ chunks/webpack-880e48e2fc817058.js     1 kB
  └ css/41aa8a2b2b181921.css               7.29 kB
```

After
```
Route (pages)                              Size     First Load JS
┌ ○ /                                      34.6 kB         113 kB
├   /_app                                  0 B            78.3 kB
└ ○ /404                                   182 B          78.5 kB
+ First Load JS shared by all              85.6 kB
  ├ chunks/framework-2647c7e378e02044.js   45.2 kB
  ├ chunks/main-1cd0f54cc68f94aa.js        27 kB
  ├ chunks/pages/_app-68b552c48a55f428.js  5.13 kB
  ├ chunks/webpack-880e48e2fc817058.js     1 kB
  └ css/a04992481059eb80.css               7.3 kB
```

</details>

<details><summary>Build Stats: playground</summary>

Before
```
Route (app)                                Size     First Load JS
┌ ○ /                                      0 B                0 B
├ ○ /login                                 0 B                0 B
└ ○ /signup                                0 B                0 B
+ First Load JS shared by all              82.8 kB
  ├ chunks/837-6030326ca5f785ef.js         80.4 kB
  ├ chunks/main-app-b990bd463c1682a5.js    217 B
  └ chunks/webpack-967f29203e361fcc.js     2.16 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   178 B          81.3 kB
+ First Load JS shared by all              81.1 kB
  ├ chunks/main-829f724b2c2d74e7.js        78.8 kB
  ├ chunks/pages/_app-ee185f83cd769c40.js  192 B
  └ chunks/webpack-967f29203e361fcc.js     2.16 kB
```

After
```
Route (app)                                Size     First Load JS
┌ ○ /                                      0 B                0 B
├ ○ /login                                 0 B                0 B
└ ○ /signup                                0 B                0 B
+ First Load JS shared by all              75.8 kB
  ├ chunks/757-9c2a460bb02e0f4f.js         65.5 kB
  ├ chunks/901-21bd003a0bcd078c.js         7.93 kB
  ├ chunks/main-app-07558ef4ed89c5b4.js    204 B
  └ chunks/webpack-6a948f17753cea2e.js     2.16 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   179 B          90.9 kB
+ First Load JS shared by all              90.7 kB
  ├ chunks/main-32a87a4adb794685.js        88.4 kB
  ├ chunks/pages/_app-5c5d79c30c1fd3df.js  192 B
  └ chunks/webpack-6a948f17753cea2e.js     2.16 kB
```

</details>

### CODE REVIEW

**Comment by shadcn** [comment]
Woah! This is a big effort. Thank you.

Let me know when ready I'll review.

**Comment by elliot** [comment]
Thanks @shadcn. Currently blocked on https://github.com/contentlayerdev/contentlayer/issues/386 for the `www` app but I'll look at upgrading that in a separate PR shortly

**Comment by elliot** [comment]
@shadcn ready for review

**Comment by elliot** [comment]
Closed by #180 

Thanks @shadcn for all your work!

**Pull request closed without merging**
