### PR TITLE
feat(button): support render delegation with asChild parameter

### PR DESCRIPTION
**Pull request by emrosenf**
This PR adds the `asChild` parameter to `Button`, which renders the child component with the `Button`'s behavior and styles, reducing DOM nodes.

Example:

```
<Button asChild variant="ghost">
  <Link to="/login">Login</Link>
</Button>
```

This pattern is very common in frameworks (e.g. Next.js, Remix, etc) and is used throughout @radix-ui/primitives

[Here is a blogpost on implementation](https://medium.com/@bryanmylee/aschild-in-react-svelte-vue-and-solid-for-render-delegation-645c73650ced)

### CODE REVIEW

**Comment by shadcn** [comment]
@emrosenf This is brilliant 👏 

I'll review and merge.

**Comment by emrosenf** [comment]
Sweet! Let me know if you need help with the documentation

**Comment by shadcn** [comment]
> Sweet! Let me know if you need help with the documentation

Yeah. Let's update this section with your example above: https://ui.shadcn.com/docs/components/button#link

(Can you also run `pnpm format:write` to fix the formatting issues please?)

Thank you.

**Comment by emrosenf** [comment]
> > Sweet! Let me know if you need help with the documentation
> 
> Yeah. Let's update this section with your example above: https://ui.shadcn.com/docs/components/button#link
> 
> (Can you also run `pnpm format:write` to fix the formatting issues please?)
> 
> Thank you.

Good call. Done. You can consider adding `format` as a commit hook so your PRs all come in formatted correctly.

**Review by shadcn — APPROVED** [review]
Thank you.

**Pull request merged**
