### PR TITLE
feat: toggle theme icon at the same time

### PR DESCRIPTION
**Pull request by Zebeqo**
What do you think? I used this method on my [website](https://www.bangumi.app/), doing well.

### CODE REVIEW

**Comment by shadcn** [comment]
Interesting. How does this handle selecting system or cycling through modes?

**Comment by Zebeqo** [comment]
https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch

I just remembered. The problem is actually explained on the readme.

**Comment by Zebeqo** [comment]
Sorry, I forgot to update the mode-toggle. But this will report a hydration error in development.

Couldn't solve it, for some reason this wasn't showing up in my project.

**Comment by Angelfire** [comment]
This worked for me:
```js
"use client"

import { useEffect, useState } from "react"
import { useTheme } from "next-themes"

import { Laptop, Moon, Sun } from "@/components/icons"
import { Button } from "@/components/ui/Button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/DropdownMenu"

export function ThemeToggle() {
  const [mounted, setMounted] = useState(false)
  const { setTheme, theme } = useTheme()

  // useEffect only runs on the client, so now we can safely show the UI
  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) {
    return null
  }

  const Icon = {
    system: Laptop,
    light: Sun,
    dark: Moon,
  }

  const ThemeIcon = Icon[theme]

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="sm">
          <ThemeIcon className="hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-100" />
          <span className="sr-only">Toggle theme</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" forceMount>
        <DropdownMenuItem onClick={() => setTheme("light")}>
          <Sun className="mr-2 h-4 w-4" />
          <span>Light</span>
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme("dark")}>
          <Moon className="mr-2 h-4 w-4" />
          <span>Dark</span>
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme("system")}>
          <Laptop className="mr-2 h-4 w-4" />
          <span>System</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
```

There is a small problem with this line:
`const ThemeIcon = Icon[theme]`

> Type 'undefined' cannot be used as an index type.

**Pull request closed without merging**
