### PR TITLE
fix(www/command-menu): command menu keybinding not working

### PR DESCRIPTION
**Pull request by vedantnn71**
prevent the default action of the browser in order to open the command menu.

https://user-images.githubusercontent.com/70624701/219858176-824cfc1b-c114-4d32-bd29-2d60fee5adbd.mp4

### CODE REVIEW

**Comment by shadcn** [comment]
This handles Windows machine? Can anyone test and confirm please?

**Comment by vedantnn71** [comment]
@shadcn yeah it handles windows and linux machines, currently the keybinding is working on macos only.

**Review by shadcn — APPROVED** [review]
Awesome. Thanks for the fix @vedantnn71. Appreciate it!

**Comment by vedantnn71** [comment]
No problem @shadcn!

**Pull request merged**
