### PR TITLE
fix(examples/button): asChild link

### LINKED ISSUE #564: Button asChild example redirecting to 404 page, rick roll opportunity?
The asChild example (https://ui.shadcn.com/docs/components/button) redirects to a nonexistent page.

### PR DESCRIPTION
**Pull request by JoltCode**
Fixes #564

### CODE REVIEW

**Comment by jocarrd** [comment]
:thinking:

**Comment by dan5py** [comment]
Just why? 😂

**Comment by kevinmitch14** [comment]
Button docs don't mention external links and asChild example directs to broken URL #480

**Comment by JoltCode** [comment]
Ah beat me to it 😅

**Pull request closed without merging**
