### PR TITLE
opacity issues with tailwind bg #560

### PR DESCRIPTION
**Pull request by areebbbb**

### CODE REVIEW

**Comment by jocarrd** [comment]
Interesting, please provide a brief description of the improvement so that I can understand it better.

**Comment by areebbbb** [comment]
currently after update
image
previously before update
image

**Comment by dan5py** [comment]
I still don't understand why not just use `bg-[#ff0000]/50`

**Comment by areebbbb** [comment]
it will work fine in this way but we are using hsl variables in this project either we have to use hex variable or for hsl we would need to change to legacy way of tailwind cause bg-primary/90 will not work with hsl variables

**Comment by dan5py** [comment]
So tell me if I got it right:

You want to use `bg-primary/90` with this configuration:

```css
/* globals.css */
@layer base {
  :root {
    --primary: 222.2 47.4% 11.2%;
  } 
}
```

```javascript
/* tailwind.config.js*/
colors: {
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
}
```

**Comment by areebbbb** [comment]
It is working in the playground but it is not working in my project I had to use the other but thanks

**Comment by samuelpetroline** [comment]
I'm having the exact same problem. What fixed for me was changing the `tailwind.config.ts` colors from `hsl(var(--primary))` to `hsla(var(--primary))`

**Comment by areebbbb** [comment]
should we create a PR about it or something?

**Comment by ImamAlfariziSyahputra** [comment]
> I'm having the exact same problem. What fixed for me was changing the `tailwind.config.ts` colors from `hsl(var(--primary))` to `hsla(var(--primary))`

i was facing this opacity issue. but after using hsla(), it's fixed! now my background-color working fine with opacity

**Pull request closed without merging**
