### PR TITLE
fix: class name typo

### PR DESCRIPTION
**Pull request by TatTran22**

### CODE REVIEW

**Review by shadcn — APPROVED** [review]
Good catch. This was a a previous iteration.

**Comment by shadcn** [comment]
Looks like there's a minor lint issue. Can you run `pnpm lint`? I can fix as well if pnpm lint is not working for you.

**Comment by shadcn** [comment]
Sorry didn't mean to close this.

**Comment by TatTran22** [comment]
there are a few errors about the class order:
www:lint: ./app/sink/page.tsx
www:lint: 66:18  Error: Invalid Tailwind CSS classnames order  tailwindcss/classnames-order
www:lint: ./components/ui/command.tsx
www:lint: 48:18  Error: Invalid Tailwind CSS classnames order  tailwindcss/classnames-order

**Comment by TatTran22** [comment]
I suggest installing eslint-config-prettier and eslint-plugin-tailwindcss to enable automatic error fixing by ESLint.

**Pull request merged**
