### PR TITLE
docs(www): add vite docs

### PR DESCRIPTION
**Pull request by NikharPandya**
Added Vite docs that use a Vite community-approved template with React, Typescript, Tailwind, Eslint, Postcss, Prefixer.
I added a vite.mdx with a similar structure to nextjs.mdx and also updated the tabs on the index page.

### CODE REVIEW

**Comment by dan5py** [comment]
Hi @NikharPandya, I really appreciate your work but a PR for the vite docs has already been opened by @samuelkurdz (#714). He just needs to apply the new layout to it and it's done. Thanks anyway.

**Comment by NikharPandya** [comment]
ohh my-bad i should have looked before. No worries,  Great work @samuelkurdz. 
and @dan5py do we need guide for astro ?

**Comment by dan5py** [comment]
> do we need guide for astro ?

@NikharPandya  Yeah we do.

**Comment by NikharPandya** [comment]
> > do we need guide for astro ?
> 
> @NikharPandya Yeah we do.

let me know once #714  is merged will merge mine.

**Comment by shadcn** [comment]
@dan5py I've restructure the installation docs a bit.

@NikharPandya Yes would be awesome to have docs for Astro.

**Comment by dan5py** [comment]
> @dan5py I've restructure the installation docs a bit.

It's awesome. Just one thing the link for the manual redirects to the `remix` installation, the href on the `index.mdx` is wrong. Apart from that perfect 💯.

**Pull request closed without merging**
