### PR TITLE
fix(alert): update icon postion  in alert 

### PR DESCRIPTION
**Pull request by FathyMuhamed**
**before**
image

**after**
image

### CODE REVIEW

**Comment by dan5py** [comment]
This wouldn't fix the issue. I already explained the problem with Firefox in this issue #627.

If you want to fix this you can change make these changes in the `alert.tsx` file (remember to update both styles):

```diff
const alertVariants = cva(
- "relative w-full rounded-lg border p-4 [&:has(svg)]:pl-11 [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:left-4 [&>svg]:top-4 [&>svg]:text-foreground",
+ "relative w-full rounded-lg border p-4 [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:left-4 [&>svg]:top-4 [&>svg]:text-foreground [&>svg~*]:pl-7",
```

After changing both files you need to build the registry by running:

```bash
pnpm build:registry
```

(Thanks to @adham-coding for the hint)

**Comment by dan5py** [comment]
Be careful. You have updated only one of the themes and once you built the registry also files that you haven't changed got updated (I assume you're on Windows).
Also don't update the `pnpm-lock.yaml` please.

**Comment by FathyMuhamed** [comment]
@dan5py thanks for the guidance

**Review by shadcn — COMMENTED** [review]
@FathyMuhamed Does this fix the spacing issue on Firefox?

**Pull request closed without merging**
