### PR TITLE
docs(dialog): trigger dialog from context menu or dropdown

### PR DESCRIPTION
**Pull request by yalsayid**
Proposing to add a section to the Dialog component documentation to explain how to use a ContextMenuItem or DropdownMenuItem as a trigger for the Dialog component. This will provide clarity for other users who may struggle with this as I did. It wasn't immediate to me to wrap the ContextMenu with the Dialog as referenced [here](https://github.com/radix-ui/primitives/issues/1836).

### CODE REVIEW

**Review by shadcn — APPROVED** [review]
Helpful! Thank you.

**Comment by soulbliss** [comment]
If anyone has come here from shadcn/ui dialog notes and wondering how to show different dialogs for different menu items
```
<DropdownMenu>
  <DropdownMenuTrigger asChild>
    <Button variant="ghost" className="h-8 w-8 p-0">
      <span className="sr-only">Open menu</span>
      <MoreHorizontal className="h-4 w-4" />
    </Button>
  </DropdownMenuTrigger>
  <DropdownMenuContent align="end">
    <DropdownMenuLabel>Actions</DropdownMenuLabel>
    <Dialog>
      <DialogTrigger>
        <DropdownMenuItem onSelect={(e) => e.preventDefault()}>
          Update item
        </DropdownMenuItem>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Update form</DialogTitle>
          <DialogDescription>
            Here you can add fields to update your form
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
    <DropdownMenuSeparator />
    <Dialog>
      <DialogTrigger>
        <DropdownMenuItem onSelect={(e) => e.preventDefault()}>
          Delete item
        </DropdownMenuItem>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Are you sure absolutely sure?</DialogTitle>
          <DialogDescription>
            This action cannot be undone. This will permanently delete
            your account and remove your data from our servers.
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  </DropdownMenuContent>
</DropdownMenu>
 
 ```

**Comment by rpin-01** [comment]
@soulbliss You're my hero!

**Comment by gruckion** [comment]
> If anyone has come here from shadcn/ui dialog notes and wondering how to show different dialogs for different menu items
> 
> ```
> <DropdownMenu>
>   <DropdownMenuTrigger asChild>
>     <Button variant="ghost" className="h-8 w-8 p-0">
>       <span className="sr-only">Open menu</span>
>       <MoreHorizontal className="h-4 w-4" />
>     </Button>
>   </DropdownMenuTrigger>
>   <DropdownMenuContent align="end">
>     <DropdownMenuLabel>Actions</DropdownMenuLabel>
>     <Dialog>
>       <DialogTrigger>
>         <DropdownMenuItem onSelect={(e) => e.preventDefault()}>
>           Update item
>         </DropdownMenuItem>
>       </DialogTrigger>
>       <DialogContent>
>         <DialogHeader>
>           <DialogTitle>Update form</DialogTitle>
>           <DialogDescription>
>             Here you can add fields to update your form
>           </DialogDescription>
>         </DialogHeader>
>       </DialogContent>
>     </Dialog>
>     <DropdownMenuSeparator />
>     <Dialog>
>       <DialogTrigger>
>         <DropdownMenuItem onSelect={(e) => e.preventDefault()}>
>           Delete item
>         </DropdownMenuItem>
>       </DialogTrigger>
>       <DialogContent>
>         <DialogHeader>
>           <DialogTitle>Are you sure absolutely sure?</DialogTitle>
>           <DialogDescription>
>             This action cannot be undone. This will permanently delete
>             your account and remove your data from our servers.
>           </DialogDescription>
>         </DialogHeader>
>       </DialogContent>
>     </Dialog>
>   </DropdownMenuContent>
> </DropdownMenu>
>  
> ```

This doesn't work, if the drop down menu closes then the dialog will also close has you have it nested inside the dropdown content.

How did you get around this problem? This works.

```tsx
      <Dialog.Root>
        <DropdownMenu.Root>
          <DropdownMenu.Trigger>Dropdown Menu</DropdownMenu.Trigger>
          <DropdownMenu.Portal>
            <DropdownMenu.Content>
              <Dialog.Trigger>
                <DropdownMenu.Item>"Test"</DropdownMenu.Item>
              </Dialog.Trigger>
            </DropdownMenu.Content>
          </DropdownMenu.Portal>
        </DropdownMenu.Root>
        <Dialog.Portal>
          <Dialog.Overlay className="DialogOverlay" />
          <Dialog.Content className="DialogContent">
            This is a modal.
          </Dialog.Content>
        </Dialog.Portal>
      </Dialog.Root>
```

**Comment by florinkrasniqi** [comment]
@soulbliss @rpin-01 Still having some issues when pressing the `esc` key; Have you by any change found any workaround for that? Setting modal={false} on DropdownMenu seems to do the job but then when dialog is opened and you click the key it will close both the Dialog and the Dropdown :|

**Pull request merged**
